apiVersion: apps/v1
kind: Deployment
metadata:
  name: awx-operator
  namespace: awx
spec:
  replicas: 1
  selector:
    matchLabels:
      name: awx-operator
  template:
    metadata:
      labels:
        name: awx-operator
    spec:
      serviceAccountName: awx-operator
      containers:
        - name: awx-operator
          image: quay.io/ansible/awx-operator:latest
          imagePullPolicy: IfNotPresent
