apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: awx
  namespace: flux-system
spec:
  interval: 5m
  path: ./apps/awx
  prune: true
  wait: true
  timeout: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system # KEEP THIS
  targetNamespace: awx
